### ISSUE TITLE
Detailed plan(2.4-2.24)

### ISSUE THREAD

**Issue by sh2439** [AguaClara/floc_app#1]
## 2.4-2.10 

[Learn how to use Python](https://github.com/AguaClara/aguaclara_tutorial/wiki)  
   
[Floc size software](https://confluence.cornell.edu/display/AGUACLARA/Floc+Size+and+Count+Application+Software)  

[Paper ](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4752185/)      

## 2.11-2.17
Go through old team’s paper, figure out how to write code for it in Python

## 2.18-2.24

Tasks:
Get camera working
Image transfer (rate of photos)
Depth of field calibration 
Image processing
Counting
Finding size

**Comment by ethan92429** [comment]
@sh2439 you guys should go through the openCV tutorials [here](http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html). That'll show you setting up a camera with Python and how to do all the image processing.
