### ISSUE TITLE
Sizing and Weighing Particles

### ISSUE THREAD

**Issue by rk635** [AguaClara/floc_app#17]
Estimate the size and then find the best way to statistically weigh/count number of particles per unit volume.

**Comment by sh2439** [comment]
In "skimage" package, we used the function "label" and "regionprops" to count and size the flocs:

count:`labels=label(cleared, connectivity = 1)
print('regions number:',labels.max())`

size:`for region in regionprops(labels):
print(region.area)`

**Comment by rk635** [comment]
Still need to incorporate camera calibration to figure out actual volume in units
