### ISSUE TITLE
OpenCV/other tutorials on depth of field

### ISSUE THREAD

**Issue by medhavi27** [AguaClara/floc_app#21]
Find and replicate code on depth of field & calibration

**Comment by zhenxiao3** [comment]
http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_calibration/py_calibration.html

**Comment by zhenxiao3** [comment]
Tutorials for camera calibration: http://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_calib3d/py_table_of_contents_calib3d/py_table_of_contents_calib3d.html#py-table-of-content-calib

**Comment by zhenxiao3** [comment]
We need at least two images in order to calibrate the camera. Since we only have one floc camera, we are not sure how to make this applicable towards our app. For now, we are just trying to make a calibration function work and will apply this towards floc app in the future.
