### ISSUE TITLE
Converting old code to new code

### ISSUE THREAD

**Issue by medhavi27** [AguaClara/floc_app#3]
Reading the old FLOC app papers
Understanding what code they used for their app
Finding potential solutions on OpenCV

**Comment by rk635** [comment]
Currently testing noise reduction features: starting with application of gaussian filter, followed by inverse threshholding. We are following the general plan laid out in https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4752185/

**Comment by rk635** [comment]
We made this issue a little vague so we are closing it to document more specific changes.
