### ISSUE TITLE
New Floc Identification Method

### ISSUE THREAD

**Issue by rk635** [AguaClara/floc_app#39]
Monroe suggested a new method to identify flocs:

1. Identify all edges
2. Check if edge has "in focus" gradient change
3. Fill everything inside this closed loop

**Comment by rk635** [comment]
We are currently in the phase of writing this procedure. Afterwards we will need to test this out on multiple flocs as we will have to decide what makes a edge "in focus"

**Comment by sh2439** [comment]
We tried this method but the result is not as good as the gaussian thresholding.
