### ISSUE TITLE
OpenCV Tutorials

### ISSUE THREAD

**Issue by rk635** [AguaClara/floc_app#4]
Complete tutorials [openCV](https://opencv-python-tutroals.readthedocs.io/en/latest/py_tutorials/py_tutorials.html)

**Comment by sh2439** [comment]
We really had a hard time trying to install openCV on MacOS. Everyone got openCV on March 5th and we all can finally code what we want.

**Comment by rk635** [comment]
Completed installation of openCV3 on mac, also completed tutorial openCV python read the docs.
