### ISSUE TITLE
Camera setup: 2/21-2/27

### ISSUE THREAD

**Issue by medhavi27** [AguaClara/floc_app#6]
Connecting the camera to our computer(s)
Depth of field calibration

**Comment by monroews** [comment]
@WPennock might have a glass slide with ruler markings that can be used for this calibration.

**Comment by WPennock** [comment]
I am afraid I have not seen this slide. Do we know if past researchers had it? If so, perhaps I might find it among our camera paraphernalia.

**Comment by monroews** [comment]
Casey used this slide.

**Comment by medhavi27** [comment]
Couldn't set up the camera on the lab's computers, so now we're doing it on our own (updated in issues),
