### ISSUE TITLE
Start code to find the width of individual flocs

### ISSUE THREAD

**Issue by DanaOwens** [AguaClara/floc_app#62]
due 3/17

**Comment by natalieisak** [comment]
Starting working on this this week. However, my code kept running into errors, and at that point Richard already completed the assignment. I spent the weekend looking over his code and using it to fix my own

**Comment by DanaOwens** [comment]
The skeleton of this code can be found in Richard's code. I am currently looking through his code to get an idea of what we are going to do to find the width of each floc.

**Comment by DanaOwens** [comment]
Code is covered in the code to find number of pixels
