### ISSUE TITLE
Find the depth of field of the camera

### ISSUE THREAD

**Issue by natalieisak** [AguaClara/floc_app#63]
due 3/19-extended to 3/28

**Comment by DanaOwens** [comment]
On hold, until solutions are made

**Comment by ry275** [comment]
Still waiting for solutions!

**Comment by ry275** [comment]
Researched the camera

**Comment by ry275** [comment]
After further review, this issue has been deemed unnecessary.

**Comment by DanaOwens** [comment]
We've decided to close this issue. After setting up the camera we've decided that no matter what the depth of field is it, everything is relative.
