### ISSUE TITLE
create known turbidity solution

### ISSUE THREAD

**Issue by natalieisak** [AguaClara/floc_app#64]
3/9-Extended to 3/20

**Comment by DanaOwens** [comment]
hi this is a test comment

**Comment by DanaOwens** [comment]
I have been going back and forth with the humic acid team. At the moment, it looks like I am going to go into the lab earlier in the week and make the solutions for us to test, using their materials.

**Comment by ry275** [comment]
Still waiting on feedback from humic acid team!

**Comment by ry275** [comment]
Still waiting for the solutions!

**Comment by DanaOwens** [comment]
Rather than working with humic acid, we used clay to create a sample solution!
