### ISSUE TITLE
Figure out how the camera works

### ISSUE THREAD

**Issue by DanaOwens** [AguaClara/floc_app#69]
due 3/29

**Comment by DanaOwens** [comment]
Downloaded software to be used to take in data from the camera!

**Comment by natalieisak** [comment]
Made turbid water to test with the camera

**Comment by ry275** [comment]
Made turbid water, researched the camera

**Comment by ry275** [comment]
Downloading SpinnakerSDK software right now.

**Comment by DanaOwens** [comment]
Downloading software on desktop! Should take an hour!

**Comment by DanaOwens** [comment]
Richard called the company and we figured out the steps needed to use the camera.

**Comment by ry275** [comment]
Troubleshooted the installation of software.

**Comment by DanaOwens** [comment]
Company software is working perfectly.
