### ISSUE TITLE
Download Labview and go over old scripts

### ISSUE THREAD

**Issue by DanaOwens** [AguaClara/floc_app#72]
Due 4/11

**Comment by DanaOwens** [comment]
Downloaded Labview

**Comment by DanaOwens** [comment]
I downloaded labview and went over old scripts.. At the moment the files look like the team set up a way to run the scripts... more research is needed.

**Comment by natalieisak** [comment]
It's been helpful so far to look at this and see how previous semesters set up the app - more work is needed though!

**Comment by DanaOwens** [comment]
After talking to Monroe, we want to move away from using labview in any capacity. We are solely going to use python to access the camera.
