### ISSUE TITLE
Meeting with RA

### ISSUE THREAD

**Issue by DanaOwens** [AguaClara/floc_app#73]
Due 4/9

**Comment by DanaOwens** [comment]
Met with matt.. We decided to talk with lois to deal with our camera issues and then talk with POST to figure out how we can save our data (so that it can be retrieved wirelessly)

**Comment by natalieisak** [comment]
This was a helpful meeting since it helped clarify the difference between our subteam and POST and how we could work together

**Comment by ry275** [comment]
Was an informative meeting. Clarified the scope of the floc application. The current priority is to just be able to record data from the camera using a computer, as sending image data is too heavy-duty to send wirelessly to POST.
